- name: update workers
  hosts: k3s_cluster
  remote_user: root
  tasks:
    - name: Update
      community.general.pacman:
        update_cache: true

    - name: Upgrade
      community.general.pacman:
        upgrade: true


